### 1. Import the NUMPY package under the name np and PANDAS as pd.

In [5]:
import numpy as np
import pandas as pd

### 2. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

In [91]:
a = np.random.random((2, 3, 5))
a

array([[[0.39909175, 0.59181451, 0.29122771, 0.30033445, 0.39525774],
        [0.42543156, 0.22268506, 0.6911893 , 0.55086195, 0.13019399],
        [0.79585405, 0.15837145, 0.84842111, 0.46771292, 0.68961314]],

       [[0.16959387, 0.79284976, 0.95274611, 0.13589441, 0.37496081],
        [0.83132214, 0.07353871, 0.01777332, 0.99750581, 0.69519602],
        [0.00280168, 0.63942342, 0.38995409, 0.26912433, 0.84672838]]])

### 3. Create a 5x2x3 3-dimensional array with all values equaling 1.

In [106]:
b = np.ones((5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 4. Do a and b have the same size? How do you prove that in Python code?

In [105]:
a.size == b.size

True

### 4. Identify the max, min, and mean values in a. Assign those values to variables "d_max", "d_min", and "d_mean"

In [104]:
a_max = a.max()
a_min = a.min()
a_mean = a.mean()
print(a_max)
print(a_min)
print(a_mean)

0.9975058075620105
0.002801683217018902
0.47158245156203055


### 5. Now we want to label the values in a. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [107]:
f = np.empty((2, 3 ,5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### 6. Populate the values in f. 

    For each value in a, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    If a value in a is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
    If a value equals to d_mean, assign 50 to the corresponding value in f.
    Assign 0 to the corresponding value(s) in f for d_min in d.
    Assign 100 to the corresponding value(s) in f for d_max in d.
    In the end, f should have only the following values: 0, 25, 50, 75, and 100.
    Note: you don't have to use Numpy in this question.

In [116]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if a[i][j][k] > a_min and a[i][j][k] < a_mean:
                f[i][j][k] = 25
            elif a[i][j][k] > a_mean and a[i][j][k] < a_max:
                f[i][j][k] = 75
            elif a[i][j][k] == a_mean:
                f[i][j][k] = 50
            elif a[i][j][k] == a_min:
                f[i][j][k] = 0
            elif a[i][j][k] == a_max:
                f[i][j][k] = 100

print(a)
print('\n')
print(f)

[[[0.39909175 0.59181451 0.29122771 0.30033445 0.39525774]
  [0.42543156 0.22268506 0.6911893  0.55086195 0.13019399]
  [0.79585405 0.15837145 0.84842111 0.46771292 0.68961314]]

 [[0.16959387 0.79284976 0.95274611 0.13589441 0.37496081]
  [0.83132214 0.07353871 0.01777332 0.99750581 0.69519602]
  [0.00280168 0.63942342 0.38995409 0.26912433 0.84672838]]]


[[[ 25.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25. 100.  75.]
  [  0.  75.  25.  25.  75.]]]


Print a and f. 

Do you have your expected f?

For instance, if your a is:

    array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:

    array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

### 7. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [118]:
matriz = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

df = pd.DataFrame(matriz)
df

0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7


### 8. Rename the data frame columns based on the names in the list below.

In [120]:
colnames = ['Score_1', 'Score_2', 'Score_3', 'Score_4', 'Score_5']

df.columns = colnames
df

Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 9. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [121]:
df_135 = df[['Score_1', 'Score_3', 'Score_5']]
df_135

Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 10. From the original data frame, calculate the average Score_3 value.

In [122]:
mean3 = df['Score_3'].mean() 
mean3

56.95000000000001

### 11. Create a Pandas DataFrame from the dictionary of product orders below.

In [125]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [126]:
df2 = pd.DataFrame(orders)
df2

Description  Quantity  UnitPrice  Revenue
0              LUNCH BAG APPLE DESIGN         1       1.65     1.65
1  SET OF 60 VINTAGE LEAF CAKE CASES         24       0.55    13.20
2         RIBBON REEL STRIPES DESIGN          1       1.65     1.65
3   WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880       0.18   518.40
4    PLAYING CARDS JUBILEE UNION JACK         2       1.25     2.50
5                      POPCORN HOLDER         7       0.85     5.95
6      BOX OF VINTAGE ALPHABET BLOCKS         1      11.95    11.95
7                       PARTY BUNTING         4       4.95    19.80
8            JAZZ HEARTS ADDRESS BOOK        10       0.19     1.90
9       SET OF 4 SANTA PLACE SETTINGS        48       1.25    60.00

### 12. Calculate the total quantity ordered and revenue generated from these orders.

In [129]:
quantity = df2['Quantity'].sum()
print("Total quantity ordered:")
print(quantity)
revenue = df2['Revenue'].sum()
print("Total revenue generated:")
print(revenue)


Total quantity ordered:
2978
Total revenue generated:
637.0
